services:
    doctoc-docker:
        build:
            context: .
            dockerfile: Dockerfile
        restart: "no"
        volumes:
            - ./:/app:rw
        entrypoint: [ "doctoc" ]
        command: [ "/app/README.md" ]
